# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: 20minutes/node-11-yarn-serverless:latest

pipelines:

  branches:
    master:
      - step:
          name: 'Install and build'
          services:
            - docker
          script:
            # Modify the commands below to build your repository.
            # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
            - yarn install
            - yarn build
            - pipe: atlassian/google-cloud-storage-deploy:0.3.6
              variables:
                KEY_FILE: $GCLOUD_API_KEYFILE
                PROJECT: 'apt-bonbon-179602'
                BUCKET: 'album-figurinhas.somalabs.com.br'
                SOURCE: '-r ./build/**'